SafeFoods.WebMVC/Controllers/IngredientTagController.cs
using Microsoft.AspNet.Identity;
using SafeFoods.Data;
using SafeFoods.Models;
using SafeFoods.Models.IngredientTagModels;
using SafeFoods.Models.RecipeModels;
using SafeFoods.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SafeFoods.WebMVC.Controllers
{
    public class IngredientTagController : Controller
    {
        // GET: IngredientTag
        public ActionResult Index()
        {
            IngredientTagService service = CreateIngredientTagService();
            var model = service.GetIngredientTags();
            return View(model);
        }

        private IngredientTagService CreateIngredientTagService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new IngredientTagService(userId);
            return service;
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IngredientTagCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreateIngredientTagService();
            if (service.CreateIngredientTag(model))
            {
                return RedirectToAction("Index");
            };

            return View(model);
            
        }

        public ActionResult Details(int id)
        {
            var svc = CreateIngredientTagService();

            var model = svc.GetIngredientTagById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateIngredientTagService();

            var detail = service.GetIngredientTagById(id);
            var model = new IngredientTagEdit
            {
                IngredientTagId = detail.IngredientTagId,
                Name = detail.Name,
                DateModified = detail.DateModified

            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IngredientTagEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.IngredientTagId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateIngredientTagService();

            if (service.UpdateIngredientTag(model))
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateIngredientTagService();

            var model = svc.GetIngredientTagById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateIngredientTagService();
            service.DeleteIngredientTag(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        [ActionName("AddTagToRecipeIngList")]
        public ActionResult AddTagToRecipeIngList(int recipeId)
        {

            ViewBag.AddTagToRecipeIngList = new IngredientTagService().GetIngredientTags();
            return View();
        }


        [HttpPost]
        [ActionName("AddTagToRecipeIngList")]
        public ActionResult AddTagToRecipeIngListPost(int recipeId, IngTagModel model)
        {


            var service = CreateIngredientTagService();

            var result = service.AddIngredientTagToRecipe(recipeId,model);

            if (result== false)
            {
                return View(result);
            }

            return RedirectToAction("Index");
        }
    }

    }

SafeFoods.WebMVC/Controllers/NutritionController.cs
using Microsoft.AspNet.Identity;
using SafeFoods.Models.NutritionModels;
using SafeFoods.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SafeFoods.WebMVC.Controllers
{
    public class NutritionController : Controller
    {
        // GET: Nutrition
        public ActionResult Index()
        {
            NutritionService service = CreateNutritionService();
            var model = service.GetNutritions();
            return View(model);
        }

        private NutritionService CreateNutritionService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new NutritionService(userId);
            return service;
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int recipeId,NutritionCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreateNutritionService();

            if (service.CreateNutrition(recipeId,model))
            {
                return RedirectToAction("Index");
            };

            return View(model);

        }
        [ActionName("Details")]
        public ActionResult Details(int recipeId)
        {
            var svc = CreateNutritionService();

            var model = svc.GetNutritionById(recipeId);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateNutritionService();

            var detail = service.GetNutritionById(id);
            var model = new NutritionEdit
            {
                RecipeID = detail.RecipeID,
                Carbohydrates = detail.Carbohydrates,
                Calories = detail.Calories,
                FatGram = detail.FatGram,
                Protein = detail.Protein,
                Fiber = detail.Fiber
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, NutritionEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.RecipeID != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateNutritionService();

            if (service.UpdateNutrition(model))
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateNutritionService();

            var model = svc.GetNutritionById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateNutritionService();
            service.DeleteNutrition(id);
            return RedirectToAction("Index");
        }

 
    }
}

SafeFoods.WebMVC/Controllers/RecipeController.cs
using Microsoft.AspNet.Identity;
using SafeFoods.Data;
using SafeFoods.Models;
using SafeFoods.Models.RecipeModels;
using SafeFoods.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SafeFoods.WebMVC.Controllers
{
    [Authorize]
    public class RecipeController : Controller
    {
        // GET: Recipe
        public ActionResult Index()
        {
            RecipeService service = CreateRecipeService();
            var model = service.GetRecipes();
            return View(model);
        }

        public ActionResult IndexOwner()
        {
            RecipeService service = CreateRecipeService();
            var model = service.GetRecipesForOwner();
            return View(model);
        }

        private RecipeService CreateRecipeService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RecipeService(userId);
            return service;
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecipeCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreateRecipeService();

            if (service.CreateRecipe(model))
            {
                return RedirectToAction("Index");
            };


            return View(model);

        }

        public ActionResult FridgeSearch()
        {

            ViewBag.RecipeFridgeSearch = new IngredientTagService().GetIngredientTags();
            return View();
        }

        [HttpPost]
        //[ActionName("FridgeSearchFunctionality")]
        public ActionResult FridgeSearch(RecipeFridgeSearch model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateRecipeService();

            var result = service.FridgeSearch(model);

            if (result != null)
            {
                return RedirectToAction("FridgeSearchViewRESULT",model);
            }
            return View(model);




        }

        public ActionResult FridgeSearchViewRESULT(RecipeFridgeSearch model)
        {
            //var recipeThing = new List<RecipeDetail>();
            //foreach(var recipe in item)
            //{
            //    recipeThing.Add(CreateRecipeService().GetRecipeById(recipe.RecipeId));
            //}
            //ViewBag.Recipies = item;
            return View(CreateRecipeService().FridgeSearch(model));

        }

        public ActionResult Details(int id)
        {
            var svc = CreateRecipeService();

            var model = svc.GetRecipeById(id);

            return View(model);
        }

        public ActionResult GetAllByTag(int tagId)
        {
            var service = CreateRecipeService();
            var details = service.GetRecipesByIngredientId(tagId);

            return View(details);


        }

        public ActionResult Edit(int id)
        {
            var service = CreateRecipeService();

            var detail = service.GetRecipeById(id);
            var model = new RecipeEdit
            {
                RecipeId = detail.RecipeId,
                Name = detail.Name,
                Description = detail.Description,
                Instructions = detail.Instructions,
                PrepTime = detail.PrepTime,
                CookTime = detail.CookTime
            };
            return View(model);
        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,RecipeEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if(model.RecipeId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateRecipeService();

            if (service.UpdateRecipe(model))
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete (int id)
        {
            var svc = CreateRecipeService();

            var model = svc.GetRecipeById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateRecipeService();
            service.DeleteRecipe(id);
            return RedirectToAction("IndexOwner");
        }


    }
}

SafeFoods.WebMVC/Views/Recipe/Create.cshtml
@model SafeFoods.Models.RecipeModels.RecipeCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create Your Own Recipe</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add the following details : </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instructions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instructions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instructions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrepTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrepTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrepTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CookTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CookTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CookTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SafeFoods.WebMVC/Views/Recipe/Delete.cshtml
@model SafeFoods.Models.RecipeModels.RecipeDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RecipeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecipeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrepTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrepTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CookTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CookTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-success" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SafeFoods.WebMVC/Views/Recipe/Details.cshtml
@model SafeFoods.Models.RecipeModels.RecipeDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Recipe Detail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RecipeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecipeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrepTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrepTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CookTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CookTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RecipeId  }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SafeFoods.WebMVC/Views/Recipe/Edit.cshtml
@model SafeFoods.Models.RecipeModels.RecipeEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Recipe Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RecipeId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instructions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instructions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instructions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrepTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrepTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrepTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CookTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CookTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CookTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SafeFoods.WebMVC/Views/Recipe/FridgeSearch.cshtml
@model SafeFoods.Models.RecipeModels.RecipeFridgeSearch

@{
    ViewBag.Title = "FridgeSearch";
}

<h2>Fridge Search</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Here you can search recipes by providing what ingredients you have in your fridge.</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ingredientTagOneId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ingredientTagOneId", new SelectList(ViewBag.RecipeFridgeSearch, "IngredientTagId", ("Name")));
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ingredientTagTwoId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ingredientTagTwoId", new SelectList(ViewBag.RecipeFridgeSearch, "IngredientTagId", ("Name")));
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ingredientTagThreeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ingredientTagThreeId", new SelectList(ViewBag.RecipeFridgeSearch, "IngredientTagId", ("Name")));
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ingredientTagFourId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ingredientTagFourId", new SelectList(ViewBag.RecipeFridgeSearch, "IngredientTagId", ("Name")));
        </div>
    </div>
</div>
    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-success" />
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SafeFoods.WebMVC/Views/Recipe/FridgeSearchViewRESULT.cshtml
@model IEnumerable<SafeFoods.Models.RecipeListItem>

@{
    ViewBag.Title = "FridgeSearchViewRESULT";
}

<h2>Fridge Search RESULT</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.RecipeId)*@
            RecipeId
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Name)*@
            Name
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Description)*@
            Description
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.DateAdded)*@
            Date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RecipeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateAdded)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

SafeFoods.WebMVC/Views/Recipe/GetAllByTag.cshtml
@model IEnumerable<SafeFoods.Models.RecipeListItem>

@{
    ViewBag.Title = "IngredientsByTag";
}

<h2>Get All Recipes By Ingredients.</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RecipeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateAdded)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RecipeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateAdded)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id= item.RecipeId }) |
            @Html.ActionLink("Details", "Details", new { id=item.RecipeId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.RecipeId })
        </td>
    </tr>
}

</table>

SafeFoods.WebMVC/Views/Recipe/Index.cshtml
@model IEnumerable<SafeFoods.Models.RecipeListItem>

@{
    ViewBag.Title = "Index";
}

<h2>Recipe Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RecipeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateAdded)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RecipeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateAdded)
        </td>
        <td>

            @Html.ActionLink("Details", "Details", new { id = item.RecipeId }) |
            @Html.ActionLink("See Nutrition", "Details","Nutrition", new { RecipeId = item.RecipeId },null)

        </td>
    </tr>
}

</table>

SafeFoods.WebMVC/Views/Recipe/IndexOwner.cshtml
@model IEnumerable<SafeFoods.Models.RecipeListItem>

@{
    ViewBag.Title = "IndexOwner";
    ViewBag.Title = "CheckParameters";
}

<h2>My Recipe Portfolio</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RecipeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateAdded)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RecipeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateAdded)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.RecipeId }) |
            @Html.ActionLink("Details", "Details", new { id = item.RecipeId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.RecipeId }) |
            @*@Html.ActionLink("Add Ingredients", "AddTagToRecipeIngList", "IngredientTagController", new { RecipeId = item.RecipeId })*@ 
            @Html.ActionLink("Add Ingredient Tags", "AddTagToRecipeIngList", "IngredientTag", new { recipeId = item.RecipeId },null) |
            @Html.ActionLink("Add Nutrition Details", "Create", "Nutrition", new { recipeId = item.RecipeId }, null)


        </td>
    </tr>
}

</table>